language: go

go:
  - "1.11.x"

os:
  - linux
  - osx
  - windows

env:
  - GO111MODULE=on

script:
  - test "$TRAVIS_OS_NAME" == "windows" || diff -u <(echo -n) <(gofmt -d $(git ls-files '*.go'))
  - go vet ./...
  - go test -race ./...
