language: go

go:
  - "1.11.x"

os:
  - linux
  - osx

before_install:
  - go get -u github.com/kardianos/govendor

script:
  - diff -u <(echo -n) <(gofmt -d $(git ls-files '*.go'))
  - go vet ./...
  - go test -race ./...
